name: Keep Streamlit App Alive

on:
  schedule:
    # Esegue il job ogni 2 ore (fornendo un ampio margine di sicurezza rispetto alle 12 ore di stop)
    - cron: '0 */2 * * *'
  workflow_dispatch: # Mette a disposizione il pulsante per avviarlo manualmente

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Invia chiamata HTTP all'app Streamlit
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://expensepereport.streamlit.app/
